-- Automatically generated by term_keycodes script

function set_default(object, key)
    if rawget(object, key) ~= nil then
        return rawget(object, key)
    end
    rawset(object, key, {})
    return rawget(object, key)
end

local mod_map = {}
setmetatable(mod_map, {__index=set_default})

local function get_modifier_bits(modifiers)
    local mod_values = {S=1, A=2, C=4, D=8}
    local mod_bits = 0
    for mod, _ in pairs(modifiers) do
        if mod_values[mod] then
            mod_bits = mod_bits + mod_values[mod]
        end
    end
    return mod_bits
end

local function get_codepoint(key, modifiers)
    modifiers = modifiers or {}
    local mod_bits = get_modifier_bits(modifiers)
    return mod_map[key][mod_bits]
end

local function encode(key, modifiers)
    local codepoint = get_codepoint(key, modifiers)
    if codepoint then
        return ("<Char-%u>"):format(codepoint)
    end
    return nil
end

mod_map[ [==[<F13>]==] ][get_modifier_bits({})] = 58624
mod_map[ [==[<F14>]==] ][get_modifier_bits({})] = 58625
mod_map[ [==[<F15>]==] ][get_modifier_bits({})] = 58626
mod_map[ [==[<F16>]==] ][get_modifier_bits({})] = 58627
mod_map[ [==[<F17>]==] ][get_modifier_bits({})] = 58628
mod_map[ [==[<F18>]==] ][get_modifier_bits({})] = 58629
mod_map[ [==[<F19>]==] ][get_modifier_bits({})] = 58630
mod_map[ [==[<F20>]==] ][get_modifier_bits({})] = 58631
mod_map[ [==[<F21>]==] ][get_modifier_bits({})] = 58632
mod_map[ [==[<F22>]==] ][get_modifier_bits({})] = 58633
mod_map[ [==[<F23>]==] ][get_modifier_bits({})] = 58634
mod_map[ [==[<F24>]==] ][get_modifier_bits({})] = 58635
mod_map[ [==[<F13>]==] ][get_modifier_bits({S=true})] = 58636
mod_map[ [==[<F14>]==] ][get_modifier_bits({S=true})] = 58637
mod_map[ [==[<F15>]==] ][get_modifier_bits({S=true})] = 58638
mod_map[ [==[<F16>]==] ][get_modifier_bits({S=true})] = 58639
mod_map[ [==[<F17>]==] ][get_modifier_bits({S=true})] = 58640
mod_map[ [==[<F18>]==] ][get_modifier_bits({S=true})] = 58641
mod_map[ [==[<F19>]==] ][get_modifier_bits({S=true})] = 58642
mod_map[ [==[<F20>]==] ][get_modifier_bits({S=true})] = 58643
mod_map[ [==[<F21>]==] ][get_modifier_bits({S=true})] = 58644
mod_map[ [==[<F22>]==] ][get_modifier_bits({S=true})] = 58645
mod_map[ [==[<F23>]==] ][get_modifier_bits({S=true})] = 58646
mod_map[ [==[<F24>]==] ][get_modifier_bits({S=true})] = 58647
mod_map[ [==[<BS>]==] ][get_modifier_bits({S=true})] = 58648
mod_map[ [==[<Enter>]==] ][get_modifier_bits({S=true})] = 58649
mod_map[ [==[<Space>]==] ][get_modifier_bits({S=true})] = 58650
mod_map[ [==[<Tab>]==] ][get_modifier_bits({C=true})] = 58651
mod_map[ [==[<BS>]==] ][get_modifier_bits({C=true})] = 58652
mod_map[ [==[<Del>]==] ][get_modifier_bits({C=true})] = 58653
mod_map[ [==[<Esc>]==] ][get_modifier_bits({C=true})] = 58654
mod_map[ [==[<Enter>]==] ][get_modifier_bits({C=true})] = 58655
mod_map[ [==[<Space>]==] ][get_modifier_bits({C=true})] = 58656
mod_map[ [==[<Left>]==] ][get_modifier_bits({C=true})] = 58657
mod_map[ [==[<Right>]==] ][get_modifier_bits({C=true})] = 58658
mod_map[ [==[<Up>]==] ][get_modifier_bits({C=true})] = 58659
mod_map[ [==[<Down>]==] ][get_modifier_bits({C=true})] = 58660
mod_map[ [==[<Home>]==] ][get_modifier_bits({C=true})] = 58661
mod_map[ [==[<End>]==] ][get_modifier_bits({C=true})] = 58662
mod_map[ [==[<PageUp>]==] ][get_modifier_bits({C=true})] = 58663
mod_map[ [==[<PageDown>]==] ][get_modifier_bits({C=true})] = 58664
mod_map[ [==[<F1>]==] ][get_modifier_bits({C=true})] = 58665
mod_map[ [==[<F2>]==] ][get_modifier_bits({C=true})] = 58666
mod_map[ [==[<F3>]==] ][get_modifier_bits({C=true})] = 58667
mod_map[ [==[<F4>]==] ][get_modifier_bits({C=true})] = 58668
mod_map[ [==[<F5>]==] ][get_modifier_bits({C=true})] = 58669
mod_map[ [==[<F6>]==] ][get_modifier_bits({C=true})] = 58670
mod_map[ [==[<F7>]==] ][get_modifier_bits({C=true})] = 58671
mod_map[ [==[<F8>]==] ][get_modifier_bits({C=true})] = 58672
mod_map[ [==[<F9>]==] ][get_modifier_bits({C=true})] = 58673
mod_map[ [==[<F10>]==] ][get_modifier_bits({C=true})] = 58674
mod_map[ [==[<F11>]==] ][get_modifier_bits({C=true})] = 58675
mod_map[ [==[<F12>]==] ][get_modifier_bits({C=true})] = 58676
mod_map[ [==[<F13>]==] ][get_modifier_bits({C=true})] = 58677
mod_map[ [==[<F14>]==] ][get_modifier_bits({C=true})] = 58678
mod_map[ [==[<F15>]==] ][get_modifier_bits({C=true})] = 58679
mod_map[ [==[<F16>]==] ][get_modifier_bits({C=true})] = 58680
mod_map[ [==[<F17>]==] ][get_modifier_bits({C=true})] = 58681
mod_map[ [==[<F18>]==] ][get_modifier_bits({C=true})] = 58682
mod_map[ [==[<F19>]==] ][get_modifier_bits({C=true})] = 58683
mod_map[ [==[<F20>]==] ][get_modifier_bits({C=true})] = 58684
mod_map[ [==[<F21>]==] ][get_modifier_bits({C=true})] = 58685
mod_map[ [==[<F22>]==] ][get_modifier_bits({C=true})] = 58686
mod_map[ [==[<F23>]==] ][get_modifier_bits({C=true})] = 58687
mod_map[ [==[<F24>]==] ][get_modifier_bits({C=true})] = 58688
mod_map[ [==[h]==] ][get_modifier_bits({C=true})] = 58689
mod_map[ [==[i]==] ][get_modifier_bits({C=true})] = 58690
mod_map[ [==[j]==] ][get_modifier_bits({C=true})] = 58691
mod_map[ [==[m]==] ][get_modifier_bits({C=true})] = 58692
mod_map[ [==[s]==] ][get_modifier_bits({C=true})] = 58693
mod_map[ [==[`]==] ][get_modifier_bits({C=true})] = 58694
mod_map[ [==[1]==] ][get_modifier_bits({C=true})] = 58695
mod_map[ [==[2]==] ][get_modifier_bits({C=true})] = 58696
mod_map[ [==[3]==] ][get_modifier_bits({C=true})] = 58697
mod_map[ [==[4]==] ][get_modifier_bits({C=true})] = 58698
mod_map[ [==[5]==] ][get_modifier_bits({C=true})] = 58699
mod_map[ [==[[]==] ][get_modifier_bits({C=true})] = 58700
mod_map[ [==[7]==] ][get_modifier_bits({C=true})] = 58701
mod_map[ [==[8]==] ][get_modifier_bits({C=true})] = 58702
mod_map[ [==[9]==] ][get_modifier_bits({C=true})] = 58703
mod_map[ [==[0]==] ][get_modifier_bits({C=true})] = 58704
mod_map[ [==[;]==] ][get_modifier_bits({C=true})] = 58705
mod_map[ [==[']==] ][get_modifier_bits({C=true})] = 58706
mod_map[ [==[,]==] ][get_modifier_bits({C=true})] = 58707
mod_map[ [==[.]==] ][get_modifier_bits({C=true})] = 58708
mod_map[ [==[A]==] ][get_modifier_bits({C=true})] = 58709
mod_map[ [==[B]==] ][get_modifier_bits({C=true})] = 58710
mod_map[ [==[C]==] ][get_modifier_bits({C=true})] = 58711
mod_map[ [==[D]==] ][get_modifier_bits({C=true})] = 58712
mod_map[ [==[E]==] ][get_modifier_bits({C=true})] = 58713
mod_map[ [==[F]==] ][get_modifier_bits({C=true})] = 58714
mod_map[ [==[G]==] ][get_modifier_bits({C=true})] = 58715
mod_map[ [==[H]==] ][get_modifier_bits({C=true})] = 58716
mod_map[ [==[I]==] ][get_modifier_bits({C=true})] = 58717
mod_map[ [==[J]==] ][get_modifier_bits({C=true})] = 58718
mod_map[ [==[K]==] ][get_modifier_bits({C=true})] = 58719
mod_map[ [==[L]==] ][get_modifier_bits({C=true})] = 58720
mod_map[ [==[M]==] ][get_modifier_bits({C=true})] = 58721
mod_map[ [==[N]==] ][get_modifier_bits({C=true})] = 58722
mod_map[ [==[O]==] ][get_modifier_bits({C=true})] = 58723
mod_map[ [==[P]==] ][get_modifier_bits({C=true})] = 58724
mod_map[ [==[Q]==] ][get_modifier_bits({C=true})] = 58725
mod_map[ [==[R]==] ][get_modifier_bits({C=true})] = 58726
mod_map[ [==[S]==] ][get_modifier_bits({C=true})] = 58727
mod_map[ [==[T]==] ][get_modifier_bits({C=true})] = 58728
mod_map[ [==[U]==] ][get_modifier_bits({C=true})] = 58729
mod_map[ [==[V]==] ][get_modifier_bits({C=true})] = 58730
mod_map[ [==[W]==] ][get_modifier_bits({C=true})] = 58731
mod_map[ [==[X]==] ][get_modifier_bits({C=true})] = 58732
mod_map[ [==[Y]==] ][get_modifier_bits({C=true})] = 58733
mod_map[ [==[Z]==] ][get_modifier_bits({C=true})] = 58734
mod_map[ [==[~]==] ][get_modifier_bits({C=true})] = 58735
mod_map[ [==[!]==] ][get_modifier_bits({C=true})] = 58736
mod_map[ [==[@]==] ][get_modifier_bits({C=true})] = 58737
mod_map[ [==[#]==] ][get_modifier_bits({C=true})] = 58738
mod_map[ [==[$]==] ][get_modifier_bits({C=true})] = 58739
mod_map[ [==[%]==] ][get_modifier_bits({C=true})] = 58740
mod_map[ [==[^]==] ][get_modifier_bits({C=true})] = 58741
mod_map[ [==[&]==] ][get_modifier_bits({C=true})] = 58742
mod_map[ [==[*]==] ][get_modifier_bits({C=true})] = 58743
mod_map[ [==[(]==] ][get_modifier_bits({C=true})] = 58744
mod_map[ [==[)]==] ][get_modifier_bits({C=true})] = 58745
mod_map[ [==[_]==] ][get_modifier_bits({C=true})] = 58746
mod_map[ [==[+]==] ][get_modifier_bits({C=true})] = 58747
mod_map[ [==[{]==] ][get_modifier_bits({C=true})] = 58748
mod_map[ [==[}]==] ][get_modifier_bits({C=true})] = 58749
mod_map[ [==[|]==] ][get_modifier_bits({C=true})] = 58750
mod_map[ [==[:]==] ][get_modifier_bits({C=true})] = 58751
mod_map[ [==["]==] ][get_modifier_bits({C=true})] = 58752
mod_map[ [==[<]==] ][get_modifier_bits({C=true})] = 58753
mod_map[ [==[>]==] ][get_modifier_bits({C=true})] = 58754
mod_map[ [==[?]==] ][get_modifier_bits({C=true})] = 58755
mod_map[ [==[<Tab>]==] ][get_modifier_bits({C=true, S=true})] = 58756
mod_map[ [==[<BS>]==] ][get_modifier_bits({C=true, S=true})] = 58757
mod_map[ [==[<Del>]==] ][get_modifier_bits({C=true, S=true})] = 58758
mod_map[ [==[<Esc>]==] ][get_modifier_bits({C=true, S=true})] = 58759
mod_map[ [==[<Enter>]==] ][get_modifier_bits({C=true, S=true})] = 58760
mod_map[ [==[<Space>]==] ][get_modifier_bits({C=true, S=true})] = 58761
mod_map[ [==[<Left>]==] ][get_modifier_bits({C=true, S=true})] = 58762
mod_map[ [==[<Right>]==] ][get_modifier_bits({C=true, S=true})] = 58763
mod_map[ [==[<Up>]==] ][get_modifier_bits({C=true, S=true})] = 58764
mod_map[ [==[<Down>]==] ][get_modifier_bits({C=true, S=true})] = 58765
mod_map[ [==[<Home>]==] ][get_modifier_bits({C=true, S=true})] = 58766
mod_map[ [==[<End>]==] ][get_modifier_bits({C=true, S=true})] = 58767
mod_map[ [==[<PageUp>]==] ][get_modifier_bits({C=true, S=true})] = 58768
mod_map[ [==[<PageDown>]==] ][get_modifier_bits({C=true, S=true})] = 58769
mod_map[ [==[<F1>]==] ][get_modifier_bits({C=true, S=true})] = 58770
mod_map[ [==[<F2>]==] ][get_modifier_bits({C=true, S=true})] = 58771
mod_map[ [==[<F3>]==] ][get_modifier_bits({C=true, S=true})] = 58772
mod_map[ [==[<F4>]==] ][get_modifier_bits({C=true, S=true})] = 58773
mod_map[ [==[<F5>]==] ][get_modifier_bits({C=true, S=true})] = 58774
mod_map[ [==[<F6>]==] ][get_modifier_bits({C=true, S=true})] = 58775
mod_map[ [==[<F7>]==] ][get_modifier_bits({C=true, S=true})] = 58776
mod_map[ [==[<F8>]==] ][get_modifier_bits({C=true, S=true})] = 58777
mod_map[ [==[<F9>]==] ][get_modifier_bits({C=true, S=true})] = 58778
mod_map[ [==[<F10>]==] ][get_modifier_bits({C=true, S=true})] = 58779
mod_map[ [==[<F11>]==] ][get_modifier_bits({C=true, S=true})] = 58780
mod_map[ [==[<F12>]==] ][get_modifier_bits({C=true, S=true})] = 58781
mod_map[ [==[<F13>]==] ][get_modifier_bits({C=true, S=true})] = 58782
mod_map[ [==[<F14>]==] ][get_modifier_bits({C=true, S=true})] = 58783
mod_map[ [==[<F15>]==] ][get_modifier_bits({C=true, S=true})] = 58784
mod_map[ [==[<F16>]==] ][get_modifier_bits({C=true, S=true})] = 58785
mod_map[ [==[<F17>]==] ][get_modifier_bits({C=true, S=true})] = 58786
mod_map[ [==[<F18>]==] ][get_modifier_bits({C=true, S=true})] = 58787
mod_map[ [==[<F19>]==] ][get_modifier_bits({C=true, S=true})] = 58788
mod_map[ [==[<F20>]==] ][get_modifier_bits({C=true, S=true})] = 58789
mod_map[ [==[<F21>]==] ][get_modifier_bits({C=true, S=true})] = 58790
mod_map[ [==[<F22>]==] ][get_modifier_bits({C=true, S=true})] = 58791
mod_map[ [==[<F23>]==] ][get_modifier_bits({C=true, S=true})] = 58792
mod_map[ [==[<F24>]==] ][get_modifier_bits({C=true, S=true})] = 58793
mod_map[ [==[<Tab>]==] ][get_modifier_bits({A=true})] = 58794
mod_map[ [==[<BS>]==] ][get_modifier_bits({A=true})] = 58795
mod_map[ [==[<Del>]==] ][get_modifier_bits({A=true})] = 58796
mod_map[ [==[<Esc>]==] ][get_modifier_bits({A=true})] = 58797
mod_map[ [==[<Enter>]==] ][get_modifier_bits({A=true})] = 58798
mod_map[ [==[<Space>]==] ][get_modifier_bits({A=true})] = 58799
mod_map[ [==[<Left>]==] ][get_modifier_bits({A=true})] = 58800
mod_map[ [==[<Right>]==] ][get_modifier_bits({A=true})] = 58801
mod_map[ [==[<Up>]==] ][get_modifier_bits({A=true})] = 58802
mod_map[ [==[<Down>]==] ][get_modifier_bits({A=true})] = 58803
mod_map[ [==[<Home>]==] ][get_modifier_bits({A=true})] = 58804
mod_map[ [==[<End>]==] ][get_modifier_bits({A=true})] = 58805
mod_map[ [==[<PageUp>]==] ][get_modifier_bits({A=true})] = 58806
mod_map[ [==[<PageDown>]==] ][get_modifier_bits({A=true})] = 58807
mod_map[ [==[<F1>]==] ][get_modifier_bits({A=true})] = 58808
mod_map[ [==[<F2>]==] ][get_modifier_bits({A=true})] = 58809
mod_map[ [==[<F3>]==] ][get_modifier_bits({A=true})] = 58810
mod_map[ [==[<F4>]==] ][get_modifier_bits({A=true})] = 58811
mod_map[ [==[<F5>]==] ][get_modifier_bits({A=true})] = 58812
mod_map[ [==[<F6>]==] ][get_modifier_bits({A=true})] = 58813
mod_map[ [==[<F7>]==] ][get_modifier_bits({A=true})] = 58814
mod_map[ [==[<F8>]==] ][get_modifier_bits({A=true})] = 58815
mod_map[ [==[<F9>]==] ][get_modifier_bits({A=true})] = 58816
mod_map[ [==[<F10>]==] ][get_modifier_bits({A=true})] = 58817
mod_map[ [==[<F11>]==] ][get_modifier_bits({A=true})] = 58818
mod_map[ [==[<F12>]==] ][get_modifier_bits({A=true})] = 58819
mod_map[ [==[<F13>]==] ][get_modifier_bits({A=true})] = 58820
mod_map[ [==[<F14>]==] ][get_modifier_bits({A=true})] = 58821
mod_map[ [==[<F15>]==] ][get_modifier_bits({A=true})] = 58822
mod_map[ [==[<F16>]==] ][get_modifier_bits({A=true})] = 58823
mod_map[ [==[<F17>]==] ][get_modifier_bits({A=true})] = 58824
mod_map[ [==[<F18>]==] ][get_modifier_bits({A=true})] = 58825
mod_map[ [==[<F19>]==] ][get_modifier_bits({A=true})] = 58826
mod_map[ [==[<F20>]==] ][get_modifier_bits({A=true})] = 58827
mod_map[ [==[<F21>]==] ][get_modifier_bits({A=true})] = 58828
mod_map[ [==[<F22>]==] ][get_modifier_bits({A=true})] = 58829
mod_map[ [==[<F23>]==] ][get_modifier_bits({A=true})] = 58830
mod_map[ [==[<F24>]==] ][get_modifier_bits({A=true})] = 58831
mod_map[ [==[<Tab>]==] ][get_modifier_bits({A=true, S=true})] = 58832
mod_map[ [==[<BS>]==] ][get_modifier_bits({A=true, S=true})] = 58833
mod_map[ [==[<Del>]==] ][get_modifier_bits({A=true, S=true})] = 58834
mod_map[ [==[<Esc>]==] ][get_modifier_bits({A=true, S=true})] = 58835
mod_map[ [==[<Enter>]==] ][get_modifier_bits({A=true, S=true})] = 58836
mod_map[ [==[<Space>]==] ][get_modifier_bits({A=true, S=true})] = 58837
mod_map[ [==[<Left>]==] ][get_modifier_bits({A=true, S=true})] = 58838
mod_map[ [==[<Right>]==] ][get_modifier_bits({A=true, S=true})] = 58839
mod_map[ [==[<Up>]==] ][get_modifier_bits({A=true, S=true})] = 58840
mod_map[ [==[<Down>]==] ][get_modifier_bits({A=true, S=true})] = 58841
mod_map[ [==[<Home>]==] ][get_modifier_bits({A=true, S=true})] = 58842
mod_map[ [==[<End>]==] ][get_modifier_bits({A=true, S=true})] = 58843
mod_map[ [==[<PageUp>]==] ][get_modifier_bits({A=true, S=true})] = 58844
mod_map[ [==[<PageDown>]==] ][get_modifier_bits({A=true, S=true})] = 58845
mod_map[ [==[<F1>]==] ][get_modifier_bits({A=true, S=true})] = 58846
mod_map[ [==[<F2>]==] ][get_modifier_bits({A=true, S=true})] = 58847
mod_map[ [==[<F3>]==] ][get_modifier_bits({A=true, S=true})] = 58848
mod_map[ [==[<F4>]==] ][get_modifier_bits({A=true, S=true})] = 58849
mod_map[ [==[<F5>]==] ][get_modifier_bits({A=true, S=true})] = 58850
mod_map[ [==[<F6>]==] ][get_modifier_bits({A=true, S=true})] = 58851
mod_map[ [==[<F7>]==] ][get_modifier_bits({A=true, S=true})] = 58852
mod_map[ [==[<F8>]==] ][get_modifier_bits({A=true, S=true})] = 58853
mod_map[ [==[<F9>]==] ][get_modifier_bits({A=true, S=true})] = 58854
mod_map[ [==[<F10>]==] ][get_modifier_bits({A=true, S=true})] = 58855
mod_map[ [==[<F11>]==] ][get_modifier_bits({A=true, S=true})] = 58856
mod_map[ [==[<F12>]==] ][get_modifier_bits({A=true, S=true})] = 58857
mod_map[ [==[<F13>]==] ][get_modifier_bits({A=true, S=true})] = 58858
mod_map[ [==[<F14>]==] ][get_modifier_bits({A=true, S=true})] = 58859
mod_map[ [==[<F15>]==] ][get_modifier_bits({A=true, S=true})] = 58860
mod_map[ [==[<F16>]==] ][get_modifier_bits({A=true, S=true})] = 58861
mod_map[ [==[<F17>]==] ][get_modifier_bits({A=true, S=true})] = 58862
mod_map[ [==[<F18>]==] ][get_modifier_bits({A=true, S=true})] = 58863
mod_map[ [==[<F19>]==] ][get_modifier_bits({A=true, S=true})] = 58864
mod_map[ [==[<F20>]==] ][get_modifier_bits({A=true, S=true})] = 58865
mod_map[ [==[<F21>]==] ][get_modifier_bits({A=true, S=true})] = 58866
mod_map[ [==[<F22>]==] ][get_modifier_bits({A=true, S=true})] = 58867
mod_map[ [==[<F23>]==] ][get_modifier_bits({A=true, S=true})] = 58868
mod_map[ [==[<F24>]==] ][get_modifier_bits({A=true, S=true})] = 58869
mod_map[ [==[a]==] ][get_modifier_bits({D=true})] = 58870
mod_map[ [==[b]==] ][get_modifier_bits({D=true})] = 58871
mod_map[ [==[c]==] ][get_modifier_bits({D=true})] = 58872
mod_map[ [==[d]==] ][get_modifier_bits({D=true})] = 58873
mod_map[ [==[e]==] ][get_modifier_bits({D=true})] = 58874
mod_map[ [==[f]==] ][get_modifier_bits({D=true})] = 58875
mod_map[ [==[g]==] ][get_modifier_bits({D=true})] = 58876
mod_map[ [==[h]==] ][get_modifier_bits({D=true})] = 58877
mod_map[ [==[i]==] ][get_modifier_bits({D=true})] = 58878
mod_map[ [==[j]==] ][get_modifier_bits({D=true})] = 58879
mod_map[ [==[k]==] ][get_modifier_bits({D=true})] = 58880
mod_map[ [==[l]==] ][get_modifier_bits({D=true})] = 58881
mod_map[ [==[m]==] ][get_modifier_bits({D=true})] = 58882
mod_map[ [==[n]==] ][get_modifier_bits({D=true})] = 58883
mod_map[ [==[o]==] ][get_modifier_bits({D=true})] = 58884
mod_map[ [==[p]==] ][get_modifier_bits({D=true})] = 58885
mod_map[ [==[q]==] ][get_modifier_bits({D=true})] = 58886
mod_map[ [==[r]==] ][get_modifier_bits({D=true})] = 58887
mod_map[ [==[s]==] ][get_modifier_bits({D=true})] = 58888
mod_map[ [==[t]==] ][get_modifier_bits({D=true})] = 58889
mod_map[ [==[u]==] ][get_modifier_bits({D=true})] = 58890
mod_map[ [==[v]==] ][get_modifier_bits({D=true})] = 58891
mod_map[ [==[w]==] ][get_modifier_bits({D=true})] = 58892
mod_map[ [==[x]==] ][get_modifier_bits({D=true})] = 58893
mod_map[ [==[y]==] ][get_modifier_bits({D=true})] = 58894
mod_map[ [==[z]==] ][get_modifier_bits({D=true})] = 58895
mod_map[ [==[`]==] ][get_modifier_bits({D=true})] = 58896
mod_map[ [==[1]==] ][get_modifier_bits({D=true})] = 58897
mod_map[ [==[2]==] ][get_modifier_bits({D=true})] = 58898
mod_map[ [==[3]==] ][get_modifier_bits({D=true})] = 58899
mod_map[ [==[4]==] ][get_modifier_bits({D=true})] = 58900
mod_map[ [==[5]==] ][get_modifier_bits({D=true})] = 58901
mod_map[ [==[6]==] ][get_modifier_bits({D=true})] = 58902
mod_map[ [==[7]==] ][get_modifier_bits({D=true})] = 58903
mod_map[ [==[8]==] ][get_modifier_bits({D=true})] = 58904
mod_map[ [==[9]==] ][get_modifier_bits({D=true})] = 58905
mod_map[ [==[0]==] ][get_modifier_bits({D=true})] = 58906
mod_map[ [==[-]==] ][get_modifier_bits({D=true})] = 58907
mod_map[ [==[=]==] ][get_modifier_bits({D=true})] = 58908
mod_map[ [==[[]==] ][get_modifier_bits({D=true})] = 58909
mod_map[ [==[]]==] ][get_modifier_bits({D=true})] = 58910
mod_map[ [==[\]==] ][get_modifier_bits({D=true})] = 58911
mod_map[ [==[;]==] ][get_modifier_bits({D=true})] = 58912
mod_map[ [==[']==] ][get_modifier_bits({D=true})] = 58913
mod_map[ [==[,]==] ][get_modifier_bits({D=true})] = 58914
mod_map[ [==[.]==] ][get_modifier_bits({D=true})] = 58915
mod_map[ [==[/]==] ][get_modifier_bits({D=true})] = 58916
mod_map[ [==[<Tab>]==] ][get_modifier_bits({D=true})] = 58917
mod_map[ [==[<BS>]==] ][get_modifier_bits({D=true})] = 58918
mod_map[ [==[<Del>]==] ][get_modifier_bits({D=true})] = 58919
mod_map[ [==[<Esc>]==] ][get_modifier_bits({D=true})] = 58920
mod_map[ [==[<Enter>]==] ][get_modifier_bits({D=true})] = 58921
mod_map[ [==[<Space>]==] ][get_modifier_bits({D=true})] = 58922
mod_map[ [==[<Left>]==] ][get_modifier_bits({D=true})] = 58923
mod_map[ [==[<Right>]==] ][get_modifier_bits({D=true})] = 58924
mod_map[ [==[<Up>]==] ][get_modifier_bits({D=true})] = 58925
mod_map[ [==[<Down>]==] ][get_modifier_bits({D=true})] = 58926
mod_map[ [==[<Home>]==] ][get_modifier_bits({D=true})] = 58927
mod_map[ [==[<End>]==] ][get_modifier_bits({D=true})] = 58928
mod_map[ [==[<PageUp>]==] ][get_modifier_bits({D=true})] = 58929
mod_map[ [==[<PageDown>]==] ][get_modifier_bits({D=true})] = 58930
mod_map[ [==[<F1>]==] ][get_modifier_bits({D=true})] = 58931
mod_map[ [==[<F2>]==] ][get_modifier_bits({D=true})] = 58932
mod_map[ [==[<F3>]==] ][get_modifier_bits({D=true})] = 58933
mod_map[ [==[<F4>]==] ][get_modifier_bits({D=true})] = 58934
mod_map[ [==[<F5>]==] ][get_modifier_bits({D=true})] = 58935
mod_map[ [==[<F6>]==] ][get_modifier_bits({D=true})] = 58936
mod_map[ [==[<F7>]==] ][get_modifier_bits({D=true})] = 58937
mod_map[ [==[<F8>]==] ][get_modifier_bits({D=true})] = 58938
mod_map[ [==[<F9>]==] ][get_modifier_bits({D=true})] = 58939
mod_map[ [==[<F10>]==] ][get_modifier_bits({D=true})] = 58940
mod_map[ [==[<F11>]==] ][get_modifier_bits({D=true})] = 58941
mod_map[ [==[<F12>]==] ][get_modifier_bits({D=true})] = 58942
mod_map[ [==[<F13>]==] ][get_modifier_bits({D=true})] = 58943
mod_map[ [==[<F14>]==] ][get_modifier_bits({D=true})] = 58944
mod_map[ [==[<F15>]==] ][get_modifier_bits({D=true})] = 58945
mod_map[ [==[<F16>]==] ][get_modifier_bits({D=true})] = 58946
mod_map[ [==[<F17>]==] ][get_modifier_bits({D=true})] = 58947
mod_map[ [==[<F18>]==] ][get_modifier_bits({D=true})] = 58948
mod_map[ [==[<F19>]==] ][get_modifier_bits({D=true})] = 58949
mod_map[ [==[<F20>]==] ][get_modifier_bits({D=true})] = 58950
mod_map[ [==[<F21>]==] ][get_modifier_bits({D=true})] = 58951
mod_map[ [==[<F22>]==] ][get_modifier_bits({D=true})] = 58952
mod_map[ [==[<F23>]==] ][get_modifier_bits({D=true})] = 58953
mod_map[ [==[<F24>]==] ][get_modifier_bits({D=true})] = 58954
mod_map[ [==[A]==] ][get_modifier_bits({D=true})] = 58955
mod_map[ [==[B]==] ][get_modifier_bits({D=true})] = 58956
mod_map[ [==[C]==] ][get_modifier_bits({D=true})] = 58957
mod_map[ [==[D]==] ][get_modifier_bits({D=true})] = 58958
mod_map[ [==[E]==] ][get_modifier_bits({D=true})] = 58959
mod_map[ [==[F]==] ][get_modifier_bits({D=true})] = 58960
mod_map[ [==[G]==] ][get_modifier_bits({D=true})] = 58961
mod_map[ [==[H]==] ][get_modifier_bits({D=true})] = 58962
mod_map[ [==[I]==] ][get_modifier_bits({D=true})] = 58963
mod_map[ [==[J]==] ][get_modifier_bits({D=true})] = 58964
mod_map[ [==[K]==] ][get_modifier_bits({D=true})] = 58965
mod_map[ [==[L]==] ][get_modifier_bits({D=true})] = 58966
mod_map[ [==[M]==] ][get_modifier_bits({D=true})] = 58967
mod_map[ [==[N]==] ][get_modifier_bits({D=true})] = 58968
mod_map[ [==[O]==] ][get_modifier_bits({D=true})] = 58969
mod_map[ [==[P]==] ][get_modifier_bits({D=true})] = 58970
mod_map[ [==[Q]==] ][get_modifier_bits({D=true})] = 58971
mod_map[ [==[R]==] ][get_modifier_bits({D=true})] = 58972
mod_map[ [==[S]==] ][get_modifier_bits({D=true})] = 58973
mod_map[ [==[T]==] ][get_modifier_bits({D=true})] = 58974
mod_map[ [==[U]==] ][get_modifier_bits({D=true})] = 58975
mod_map[ [==[V]==] ][get_modifier_bits({D=true})] = 58976
mod_map[ [==[W]==] ][get_modifier_bits({D=true})] = 58977
mod_map[ [==[X]==] ][get_modifier_bits({D=true})] = 58978
mod_map[ [==[Y]==] ][get_modifier_bits({D=true})] = 58979
mod_map[ [==[Z]==] ][get_modifier_bits({D=true})] = 58980
mod_map[ [==[~]==] ][get_modifier_bits({D=true})] = 58981
mod_map[ [==[!]==] ][get_modifier_bits({D=true})] = 58982
mod_map[ [==[@]==] ][get_modifier_bits({D=true})] = 58983
mod_map[ [==[#]==] ][get_modifier_bits({D=true})] = 58984
mod_map[ [==[$]==] ][get_modifier_bits({D=true})] = 58985
mod_map[ [==[%]==] ][get_modifier_bits({D=true})] = 58986
mod_map[ [==[^]==] ][get_modifier_bits({D=true})] = 58987
mod_map[ [==[&]==] ][get_modifier_bits({D=true})] = 58988
mod_map[ [==[*]==] ][get_modifier_bits({D=true})] = 58989
mod_map[ [==[(]==] ][get_modifier_bits({D=true})] = 58990
mod_map[ [==[)]==] ][get_modifier_bits({D=true})] = 58991
mod_map[ [==[_]==] ][get_modifier_bits({D=true})] = 58992
mod_map[ [==[+]==] ][get_modifier_bits({D=true})] = 58993
mod_map[ [==[{]==] ][get_modifier_bits({D=true})] = 58994
mod_map[ [==[}]==] ][get_modifier_bits({D=true})] = 58995
mod_map[ [==[|]==] ][get_modifier_bits({D=true})] = 58996
mod_map[ [==[:]==] ][get_modifier_bits({D=true})] = 58997
mod_map[ [==["]==] ][get_modifier_bits({D=true})] = 58998
mod_map[ [==[<]==] ][get_modifier_bits({D=true})] = 58999
mod_map[ [==[>]==] ][get_modifier_bits({D=true})] = 59000
mod_map[ [==[?]==] ][get_modifier_bits({D=true})] = 59001
mod_map[ [==[<Tab>]==] ][get_modifier_bits({D=true, S=true})] = 59002
mod_map[ [==[<BS>]==] ][get_modifier_bits({D=true, S=true})] = 59003
mod_map[ [==[<Del>]==] ][get_modifier_bits({D=true, S=true})] = 59004
mod_map[ [==[<Esc>]==] ][get_modifier_bits({D=true, S=true})] = 59005
mod_map[ [==[<Enter>]==] ][get_modifier_bits({D=true, S=true})] = 59006
mod_map[ [==[<Space>]==] ][get_modifier_bits({D=true, S=true})] = 59007
mod_map[ [==[<Left>]==] ][get_modifier_bits({D=true, S=true})] = 59008
mod_map[ [==[<Right>]==] ][get_modifier_bits({D=true, S=true})] = 59009
mod_map[ [==[<Up>]==] ][get_modifier_bits({D=true, S=true})] = 59010
mod_map[ [==[<Down>]==] ][get_modifier_bits({D=true, S=true})] = 59011
mod_map[ [==[<Home>]==] ][get_modifier_bits({D=true, S=true})] = 59012
mod_map[ [==[<End>]==] ][get_modifier_bits({D=true, S=true})] = 59013
mod_map[ [==[<PageUp>]==] ][get_modifier_bits({D=true, S=true})] = 59014
mod_map[ [==[<PageDown>]==] ][get_modifier_bits({D=true, S=true})] = 59015
mod_map[ [==[<F1>]==] ][get_modifier_bits({D=true, S=true})] = 59016
mod_map[ [==[<F2>]==] ][get_modifier_bits({D=true, S=true})] = 59017
mod_map[ [==[<F3>]==] ][get_modifier_bits({D=true, S=true})] = 59018
mod_map[ [==[<F4>]==] ][get_modifier_bits({D=true, S=true})] = 59019
mod_map[ [==[<F5>]==] ][get_modifier_bits({D=true, S=true})] = 59020
mod_map[ [==[<F6>]==] ][get_modifier_bits({D=true, S=true})] = 59021
mod_map[ [==[<F7>]==] ][get_modifier_bits({D=true, S=true})] = 59022
mod_map[ [==[<F8>]==] ][get_modifier_bits({D=true, S=true})] = 59023
mod_map[ [==[<F9>]==] ][get_modifier_bits({D=true, S=true})] = 59024
mod_map[ [==[<F10>]==] ][get_modifier_bits({D=true, S=true})] = 59025
mod_map[ [==[<F11>]==] ][get_modifier_bits({D=true, S=true})] = 59026
mod_map[ [==[<F12>]==] ][get_modifier_bits({D=true, S=true})] = 59027
mod_map[ [==[<F13>]==] ][get_modifier_bits({D=true, S=true})] = 59028
mod_map[ [==[<F14>]==] ][get_modifier_bits({D=true, S=true})] = 59029
mod_map[ [==[<F15>]==] ][get_modifier_bits({D=true, S=true})] = 59030
mod_map[ [==[<F16>]==] ][get_modifier_bits({D=true, S=true})] = 59031
mod_map[ [==[<F17>]==] ][get_modifier_bits({D=true, S=true})] = 59032
mod_map[ [==[<F18>]==] ][get_modifier_bits({D=true, S=true})] = 59033
mod_map[ [==[<F19>]==] ][get_modifier_bits({D=true, S=true})] = 59034
mod_map[ [==[<F20>]==] ][get_modifier_bits({D=true, S=true})] = 59035
mod_map[ [==[<F21>]==] ][get_modifier_bits({D=true, S=true})] = 59036
mod_map[ [==[<F22>]==] ][get_modifier_bits({D=true, S=true})] = 59037
mod_map[ [==[<F23>]==] ][get_modifier_bits({D=true, S=true})] = 59038
mod_map[ [==[<F24>]==] ][get_modifier_bits({D=true, S=true})] = 59039

return {get_codepoint=get_codepoint, encode=encode}
