# Export standard XDG environment variables
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# Make sure path includes ~/.local/bin
path_additions=("$HOME/.local/bin")
path=(${path_additions:|path} $path)
